image: drupalpod/drupalpod-gitpod-base:latest

# ddev and composer are running as part of the prebuild
# when starting a workspace all docker images are ready
tasks:
  - name: terminal
    before: |
      ddev config global --instrumentation-opt-in=true
    init: |
      ddev debug download-images
      ddev composer create drupal/recommended-project
      ddev drush si demo_umami -y
    command: |
      echo y | ddev start
      if [ -n "$DP_INSTALL_PROFILE" ]; then
        ddev drush si "$DP_INSTALL_PROFILE" -y
      fi
      gp preview $(gp url 8080)

# VScode xdebug extension
vscode:
  extensions:
    # PHP extensions.
    - felixfbecker.php-debug
    - wongjn.php-sniffer
    - neilbrayfield.php-docblocker
    - bmewburn.vscode-intelephense-client

    # Twig extensions.
    - mblode.twig-language-2

    # Bash extensions.
    - timonwong.shellcheck
    - rogalmic.bash-debug

# Set the following ports public
ports:
  # Used by ddev - local db clients
  - port: 3306
    onOpen: ignore
  # Used by MailHog
  - port: 5000
    onOpen: open-preview
  - port: 6006
    onOpen: open-preview
  - port: 6942
    onOpen: ignore
  - port: 8027
    onOpen: ignore
  # Used by phpMyAdmin
  - port: 8036
    onOpen: ignore
  # Direct-connect ddev-webserver port that is the main port
  - port: 8080
    onOpen: ignore
  # Ignore host https port
  - port: 8443
    onOpen: ignore
  # xdebug port
  - port: 9003
    onOpen: ignore

github:
  prebuilds:
    # enable for the master/default branch (defaults to true)
    master: true
    # enable for all branches in this repo (defaults to false)
    branches: true
    # enable for pull requests coming from this repo (defaults to true)
    pullRequests: true
    # enable for pull requests coming from forks (defaults to false)
    pullRequestsFromForks: true
    # add a check to pull requests (defaults to true)
    addCheck: true
    # add a "Review in Gitpod" button as a comment to pull requests (defaults to false)
    addComment: true
    # add a "Review in Gitpod" button to the pull request's description (defaults to false)
    addBadge: true
    # add a label once the prebuild is ready to pull requests (defaults to false)
    addLabel: true
